name: Feature request
description: Suggest a feature idea for QNSPECT.
labels:
  - 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request correctly.

  - type: checkboxes
    id: qnspect-version
    attributes:
      label: Latest QNSPECT version
      options:
        - label: I am running the latest QNSPECT version

  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar requests do not exist
      options:
        - label: I have searched existing issues to make sure a similar request does not exist

  - type: textarea
    id: what
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen. Ex. QNSPECT would rock even more if [...]
    validations:
      required: true

  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
